#!/bin/sh
mvn jdepend:generate
# on my workstation, JDEPEND_HOME is in ~/Library/jdepend-2.9.1
xsltproc ${JDEPEND_HOME}/contrib/jdepend2dot.xsl target/jdepend-report.xml > doc/jdepend.dot
sccmap -odoc/strong.dot doc/jdepend.dot

mkdir -p doc/circo
cp doc/jdepend.dot doc/circo/
circo -s2000 -Tsvg -O       doc/circo/jdepend.dot 
dot          -Tsvg -O       doc/jdepend.dot

cp doc/strong.dot doc/circo/
circo -s2000 -Tsvg -O       doc/circo/strong.dot
dot          -Tsvg -O       doc/strong.dot 



